/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more.
 *
 * API version:
 * Contact: office@ory.sh
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ContinueWithVerificationUI Indicates, that the UI flow could be continued by showing a verification ui
type ContinueWithVerificationUI struct {
	// Action will always be `verification_ui` set_ory_session_token ContinueWithActionSetOrySessionToken verification_ui ContinueWithActionVerificationUI
	Action string                         `json:"action"`
	Flow   ContinueWithVerificationUIFlow `json:"flow"`
}

// NewContinueWithVerificationUI instantiates a new ContinueWithVerificationUI object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContinueWithVerificationUI(action string, flow ContinueWithVerificationUIFlow) *ContinueWithVerificationUI {
	this := ContinueWithVerificationUI{}
	this.Action = action
	this.Flow = flow
	return &this
}

// NewContinueWithVerificationUIWithDefaults instantiates a new ContinueWithVerificationUI object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContinueWithVerificationUIWithDefaults() *ContinueWithVerificationUI {
	this := ContinueWithVerificationUI{}
	return &this
}

// GetAction returns the Action field value
func (o *ContinueWithVerificationUI) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ContinueWithVerificationUI) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ContinueWithVerificationUI) SetAction(v string) {
	o.Action = v
}

// GetFlow returns the Flow field value
func (o *ContinueWithVerificationUI) GetFlow() ContinueWithVerificationUIFlow {
	if o == nil {
		var ret ContinueWithVerificationUIFlow
		return ret
	}

	return o.Flow
}

// GetFlowOk returns a tuple with the Flow field value
// and a boolean to check if the value has been set.
func (o *ContinueWithVerificationUI) GetFlowOk() (*ContinueWithVerificationUIFlow, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Flow, true
}

// SetFlow sets field value
func (o *ContinueWithVerificationUI) SetFlow(v ContinueWithVerificationUIFlow) {
	o.Flow = v
}

func (o ContinueWithVerificationUI) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["action"] = o.Action
	}
	if true {
		toSerialize["flow"] = o.Flow
	}
	return json.Marshal(toSerialize)
}

type NullableContinueWithVerificationUI struct {
	value *ContinueWithVerificationUI
	isSet bool
}

func (v NullableContinueWithVerificationUI) Get() *ContinueWithVerificationUI {
	return v.value
}

func (v *NullableContinueWithVerificationUI) Set(val *ContinueWithVerificationUI) {
	v.value = val
	v.isSet = true
}

func (v NullableContinueWithVerificationUI) IsSet() bool {
	return v.isSet
}

func (v *NullableContinueWithVerificationUI) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContinueWithVerificationUI(val *ContinueWithVerificationUI) *NullableContinueWithVerificationUI {
	return &NullableContinueWithVerificationUI{value: val, isSet: true}
}

func (v NullableContinueWithVerificationUI) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContinueWithVerificationUI) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
